// swift-tools-version: 6.2
//
// The Swift half of dl-nzb that the Mac and iPhone apps share.
//
//   DlNzbKit  models, the engine protocol, the simulated engine, the stores
//             (AppModel, SettingsStore, DownloadQueue), Keychain and persistence.
//   DlNzbUI   presentation: the status line, formatters, the phase checklist,
//             the progress ring, row building blocks and the settings sections.
//
//   DlNzbFFI  UniFFI's generated Swift for the Rust engine (DlNzbCore.xcframework).
//   DlNzbRust RustEngine, the DownloadEngine over DlNzbFFI that the apps use.
//
// DlNzbKit and DlNzbUI never import the bindings: views and stores only ever
// see the Swift-native mirrors in DlNzbKit/Models. The package as a whole does
// need Frameworks/DlNzbCore.xcframework to resolve; `make -C apple xcframework`
// builds it (the kit's make targets do so when it is missing).
//
// Swift 6 language mode (the tools version's default), so strict concurrency is
// complete. Isolation is spelled out (@MainActor on the stores); there is no
// default-isolation setting.
import PackageDescription

let package = Package(
  name: "DlNzbKit",
  platforms: [.macOS(.v26), .iOS(.v26)],
  products: [
    .library(name: "DlNzbKit", targets: ["DlNzbKit"]),
    .library(name: "DlNzbUI", targets: ["DlNzbUI"]),
    .library(name: "DlNzbRust", targets: ["DlNzbRust"]),
  ],
  targets: [
    .target(name: "DlNzbKit"),
    // Resources holds the generated Rust crate licence list the
    // Acknowledgements screen reads (rust-crates.json).
    .target(name: "DlNzbUI", dependencies: ["DlNzbKit"], resources: [.process("Resources")]),

    // MARK: Engine
    //
    // The Rust engine as static libraries for aarch64-apple-darwin,
    // aarch64-apple-ios and aarch64-apple-ios-sim, with the C module DlNzbCore.
    // Built (and git-ignored) by apple/scripts/build-xcframework.sh.
    .binaryTarget(name: "DlNzbCore", path: "Frameworks/DlNzbCore.xcframework"),
    // UniFFI's generated Swift, regenerated by the same script; nonisolated
    // like every target here. The libraries the Rust code needs beyond the
    // system's defaults (rustc's native-static-libs): libc++ for unRAR (its
    // build script asks for it only on macOS), libiconv for std, and the two
    // frameworks native-tls uses.
    .target(
      name: "DlNzbFFI",
      dependencies: ["DlNzbCore"],
      linkerSettings: [
        .linkedLibrary("c++"),
        .linkedLibrary("iconv"),
        .linkedFramework("Security"),
        .linkedFramework("CoreFoundation"),
      ]),
    // RustEngine, the DownloadEngine the apps use unless launched with -simulate YES.
    .target(name: "DlNzbRust", dependencies: ["DlNzbKit", "DlNzbFFI"]),

    .testTarget(name: "DlNzbKitTests", dependencies: ["DlNzbKit"]),
    .testTarget(name: "DlNzbUITests", dependencies: ["DlNzbKit", "DlNzbUI"]),
    .testTarget(name: "DlNzbRustTests", dependencies: ["DlNzbKit", "DlNzbRust", "DlNzbFFI"], resources: [.copy("Fixtures")]),
  ]
)
